name: vigilanter_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^14.0.1
  
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  provider: ^6.1.5+1
  cloud_firestore: ^6.1.0
  shared_preferences: ^2.5.3
  camera: ^0.11.3
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  video_player: ^2.9.0
  media_store_plus: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
